services:
  - type: web
    name: fsad-backend
    runtime: docker
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: APP_ALLOWED_ORIGINS
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: FIREBASE_KEY
        sync: false
